- block:
  - name: Add alertmanager user
    user:
      name: alertmanager
      shell: /sbin/nologin

  - name: Create the alertmanager directory
    file:
      path: /opt/alertmanager
      state: directory
      owner: alertmanager
      group: alertmanager
      mode: '0755'

  - name: Download alertmanager
    get_url:
      url: "{{ alertmanager_link }}"
      dest: /tmp/alertmanager.tar.gz
      mode: '0440'
    register: result
    until: result is success
    retries: 5
    delay: 3

  - name: Unarchive alertmanager
    unarchive:
      src: /tmp/alertmanager.tar.gz
      dest: /opt/alertmanager
      owner: alertmanager
      group: alertmanager
      mode: '0755'
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Copy the alertmanager server configuration file
    copy:
      src: alertmanager.yml
      dest: /opt/alertmanager
      owner: alertmanager
      group: alertmanager
      mode: '0644'

  - name: Copy the alertmanager unit file
    copy:
      src: alertmanager.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: '0644'

  - name: Force systemd to reread configs
    systemd:
      daemon_reload: yes

  - name: Make the alertmanager service enabled and started
    systemd:
      name: alertmanager
      enabled: yes
      state: started
      
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'x86_64'
  become: yes
