- block:
  - name: Add the Prometheus user
    user:
      name: prometheus
      shell: /sbin/nologin

  - name: Create the Prometheus directory
    file:
      path: /opt/prometheus
      state: directory
      owner: prometheus
      group: prometheus
      mode: '0755'

  - name: Download Prometheus
    get_url:
      url: "{{ prometheus_link }}"
      dest: /tmp/prometheus.tar.gz
      mode: '0440'
    register: result
    until: result is success
    retries: 5
    delay: 3

  - name: Unarchive Prometheus
    unarchive:
      src: /tmp/prometheus.tar.gz
      dest: /opt/prometheus
      owner: prometheus
      group: prometheus
      mode: '0755'
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Copy the Prometheus server configuration file
    copy:
      src: prometheus.yml
      dest: /opt/prometheus
      owner: prometheus
      group: prometheus
      mode: '0644'

  - name: Copy the Prometheus unit file
    copy:
      src: prometheus.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: '0644'

  - name: Force systemd to reread configs
    systemd:
      daemon_reload: yes

  - name: Make the Prometheus service enabled and started
    systemd:
      name: prometheus
      enabled: yes
      state: started
      
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'x86_64'
  become: yes
